import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../../components/navbar/Navbar'
import Hero from '../../components/hero/Hero'
import Catalog from '../../components/catalog/Catalog'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Makan Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
     <Navbar />
     <Hero />
     <Catalog />
     </div>
    </>
  )
}

export async function getServerSideProps(){
  const {data} = await axios.get('http://localhost:300/api/meal')
  return{
    props:{
      meals: data
    }
  }
}
